# 10장 예외처리

### 10.1 예외와 예외 클래스 
---

자바에서는 에러 이외에 예외라는 것이 존재한다. 예외란, 사용자의 잘못된 조작 또는 개발자의 잘못된 코딩으로 인해 발생하는 프로그램 오류를 말한다. 

- 일반 예외 (Exeption) : 컴파일러 체크 예외라고도 하는데, 컴파일 과정에서 생겨나는 예외들을 말한다. JVM은 컴파일 과정에서 예외 처리 코드가 필요한지에 대해 검사를 한다. 


- 실행 예외 (RuntimeEexption)  : 컴파일 하는 과정에서 예외 처리 코드를 검사하지 않는 예외들, 런타임 과정에서 생겨나는 예외현상들을 얘기한다. 


일반 예외는 Exception 클래스를 상속받고, 실행 예외는 RuntionException 클래스를 상속 받는다. 

### 10.2 실행 예외
---

실행예외는 자바 컴파일러가 체크를 하지 않기 때문에 오로지 개발자의 경험에 의해서 예외 처리 코드를 삽입해야 한다. 

1. NullPointerException 
	객체 참조가 없는 경우에 생기는 예외 현상, null값을 갖는 참조 변수로 객체 접근 연산자인 "."을 사용했을 때 발생한다. 


2. ArrayIndexOutBoundsException
	배열에서 인덱스 범위를 초과하여 사용할 경우에 생겨난다. 

3. NumberFormatException
	형변환 하는 매소드를 사용하는 경우에 올바르게 변환이 되지 않을 경우에 발생하는 예외현상 


			Integer.parseInt(String s) // 주어진 문자열을 정수로 변환해서 리턴
			Double.parseDouble(String s) // 주어진 문자열을 실수로 변환해서 리턴 

> 위 같은 형변환 메소드를 사용하는 경우에 있어서 매개변수가 파싱할 수 없는 것들이 왔을 때 NumberFormatException 예외가 발생한다. 


4. ClassCastException
	억지로 타입변환을 시도하는 경우에 발생한다. 

타입 변환은 상위 클래스와 하위 클래스 간에 발생하고 구현 클래스와 인터페이스 간에도 발생한다. 

##### ClassCastException 예외를 만들지 않으려면 타입 변환 전에 타입 변환이 가능한지 instanceof 연산자를 통해 확인해 보는 것이 좋다. 


			Animal animal = new Dog();
			if(animal instanceof Dog) {

					Dog dog = (Dog) animal;
			}
			else if (animal instancof Cat) {

					Cat cat = (Cat) animal;
			}

> 위의 코드를 보면 이전에 Dog를 사용하여 animal을 만들었기 때문에 animal을 Dog로 형변환 하는데 있어서 문제가 없다. 하지만 그것을 Cat으로 형변환 하려고 한다면 예외 현상이 발생한다. 


### 10.3 예외 처리 코드 
---

* 일반적으로 try - catch - finally 블럭을 통해 예외 처리 코드를 만든다. 
	- try는 코드가 실행되는 부분이다. 여기서 예외 현상이 발생하면, 
	- catch 블록으로 이동한다. 그리고 catch 블럭 부분을 실행하고
	- finally 블럭 부분이 존재 한다면, 예외 처리를 끝내고 반드시 finally  블럭 부분을 실행하고 finally가 존재하지 않는다면 메소드는 끝이 난다. 


### 10.4 다중 catch
---

try 블록 내부에서 다양한 종류의 예외가 발생할 수 있다. 이런 경우에 여러 개의 예외 처리를 할 수 있다. 하지만 예외가 발생하면 해당 catch로 넘어가기 때문에 하나의 예외 처리로 프로그램이 종료된다. 

> 또한 예외 처리를 하는데 있어서 순서를 잘 지켜줘야 한다. 예외처리를 진행할 때 컴파일러는 차례로 예외 처리를 찾기 때문에 상위 클래스보다 하위 클래스가 위에 있다면 계속해서 하위 클래스만 예외 현상이라고 나타날 것이다. 그러나 하위 예외 클래스는 상위 예외 클래스를 상속받고 있기 때문에 적절한 예외 처리라고 볼 수 없다. 


* 멀티 catch 
	하나의 catch 블럭에서 여러개의 예외 처리를 할 수 있다. 


### 10.5 자동 리소스 닫기 
---

* try - with - resources
	위 코드를 사용하면 예외 발생 여부와 상관없이 사용했던 리소스 객체의 close()를 호출하여 리소스를 안전하게 보호해준다. 


### 10.6 예외 떠넘기기 
---

메소드 내부에서 예외가 발생할 수 있는 코드를 작성할 때 try - catch 블록으로 예외 처리를 해주는 것이 일반적이지만, 경우에 따라서는 메소드를 호출한 곳으로 예외를 떠넘길 수 있다. 


##### thorws를 사용하는 이유 : java에서는 다양한 class를 통해 코드를 작성하게 되는데 각각의 작은 class에서도 예외현상이 발생할 수 있다. 그런데 예외 현상이 발생될 가능성이 보이면 예외 처리를 해줘야 하는데, 하위 class에서도 계속적으로 예외 처리를 하게 되면 코드가 복잡해질 수 있다. 그렇기 때문에 조금 더 상위 class에 예외현상을 떠넘기고 한 곳에서 처리하려고 thorws를 사용하는 것이다. 


			public void method1 () {

					try {

							method2();

					}catch(ClassNotFoundException e) {

							System.out.prinln ("클래스가 존재하지 않습니다.");
					}
			}

			public void method2() thorws ClassNotFoundException {

					Class hi = Class.forName("hohoho");
			}


> 위 처럼 method2()에서 생길 수 있는 예외 처리를 method1()에서 처리하고 있다. 만약에 method1()가 method1() 뿐만 아니라 여러 클래스들을 호출하게 되는 경우에는 한번에 method1()에서 예외 처리를 하는 것이 조금 더 간결한 것이다. 


### 10.7 사용자 정의 예외와 예외 발생
---

기존에 존재하지 않는 예외 현상의 경우 사용자가 직접적으로 예외 처리를 만들어야 한다. 그것이 일반 예외일 경우 Exception을 상속하면 되고, 실행 예외일 경우에는 RuntimeException을 상속하면 된다. 





